option(EVE_BUILD_EDITOR "Build the EVE editor application" ON)
option(EVE_BUILD_EXAMPLE_SCENE "Build apartment character example scene" ON)
option(EVE_BUILD_WARDROBE_SLICE "Build wardrobe vertical slice application" ON)
option(EVE_BUILD_ANIME_DEMO "Build anime wardrobe demo application" ON)
option(EVE_BUILD_MOVIE_DEMO "Build rainy movie night demo" ON)
option(EVE_BUILD_RAINY_DEMO "Build rainy evening demo" ON)
option(EVE_BUILD_CREATOR_STUDIO "Build Creator Studio application" ON)
option(EVE_BUILD_WEB "Enable Web deployment tooling (WebGPU/WASM manifest generation)" ON)
option(EVE_BUILD_WEB_CHARACTER_VIEWER "Build Web Apartment Character Viewer" ON)
option(EVE_BUILD_PERSONAL_EXPORT "Build personal export demo" ON)
option(EVE_BUILD_TESTS "Build automated tests" ON)
option(EVE_LEAN_BUILD "Lean build: disable optional demos and editor targets" OFF)
option(EVE_ENABLE_VULKAN_VALIDATION "Enable Vulkan validation layers" OFF)
option(EVE_ENABLE_BENCHMARKS "Build subsystem benchmarks" OFF)

if(EVE_LEAN_BUILD)
    set(EVE_BUILD_EDITOR OFF CACHE BOOL "Lean build: skip editor" FORCE)
    set(EVE_BUILD_EXAMPLE_SCENE OFF CACHE BOOL "Lean build: skip example scene" FORCE)
    set(EVE_BUILD_WARDROBE_SLICE OFF CACHE BOOL "Lean build: skip wardrobe slice" FORCE)
    set(EVE_BUILD_ANIME_DEMO OFF CACHE BOOL "Lean build: skip anime demo" FORCE)
    set(EVE_BUILD_MOVIE_DEMO OFF CACHE BOOL "Lean build: skip movie demo" FORCE)
    set(EVE_BUILD_RAINY_DEMO OFF CACHE BOOL "Lean build: skip rainy demo" FORCE)
    set(EVE_BUILD_CREATOR_STUDIO OFF CACHE BOOL "Lean build: skip creator studio" FORCE)
    set(EVE_BUILD_WEB_CHARACTER_VIEWER OFF CACHE BOOL "Lean build: skip web viewer" FORCE)
    set(EVE_BUILD_PERSONAL_EXPORT OFF CACHE BOOL "Lean build: skip personal export" FORCE)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "")
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type" FORCE)
endif()

set(CMAKE_BUILD_TYPE "${CMAKE_BUILD_TYPE}" CACHE STRING
    "Choose the type of build: Debug Release RelWithDebInfo MinSizeRel" FORCE)
